# Generated by Django 4.1.4 on 2023-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclist',
            name='song_catagary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
